version: '3.8'
services:
  app:
    build:
      context: ./3_middleware
      dockerfile: dockerfile
    container_name: middleware_app
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: backend_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: web_server
    volumes:
      - ./2_frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge