version: '3.8'
services:
  app:
    build: ./3_middleware
    container_name: middleware_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: middleware_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  web:
    image: nginx:latest
    container_name: web_server
    volumes:
      - ./2_frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - app